#!/bin/bash

app_name="${distributions.main.baseName}"
archive_dir="$copyArchivesTo"
archive_file="\${app_name}.tar"
install_dir="$baseInstallDir/\$app_name"

rm -rf \$install_dir
mkdir \$install_dir
tar xvf \$archive_dir/\$archive_file -C \$install_dir --strip-components 1
